project:
  type: website
  output-dir: public # Standard Quarto output directory
  resources: 
    - "static/**"
# bibliography: publications/references.bib # Add bibliography

website:
  title: "Ander Egurtzegi"
  site-url: https://egurtzegi.github.io
  search: 
    location: navbar
    type: overlay
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: publications/index.qmd
        text: Publications
      - href: talks/index.qmd
        text: Talks
      - href: projects/index.qmd
        text: Projects
      - href: teaching/index.qmd
        text: Teaching
      - href: index.qmd#contact
        text: Contact
      - href: static/files/EgurtzegiCV.pdf
        text: CV
  page-footer:
    center: "© Ander Egurtzegi, 2025"
    right: ""

format:
  html:
    theme:
      light: [bootstrap, custom-light.scss]
      dark: [bootstrap, custom-dark.scss]
    toc: true
    page-layout: article
    html-math-method: katex
    header-includes: |
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
    # include-in-header:
    #   - text: |
    #       <style>
    #         .container-fluid {
    #           max-width: 1200px !important;
    #         }
    #         .page-layout-full .quarto-title-block .quarto-title-banner {
    #           padding: 0;
    #           max-width: 1200px;
    #           margin: 0 auto;
    #         }
    #       </style>
    # include-after-body:
    #   - custom.js # Include our custom JavaScript --- Commented out
    # filters:
    #   - grouped_bib.lua



